baseURL = "/"
defaultContentLanguage = "nl"
languageCode = "nl"
title = "NLX"
theme = "nlx"
googleAnalytics = ""

[[menu.main]]
    name = "NLX"
    weight = -110
    identifier = "nlx"
    url = "/"

[[menu.main]]
    name = "About"
    weight = -100
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Docs"
    weight = -90
    identifier = "docs"
    url = "https://docs.nlx.io/"

[languages]
[languages.en]
weight = 0
languageName = "EN"

[languages.nl]
weight = 1
languageName = "NL"

